const fs = require('fs');
const glob = require('glob'); // Not available? We can use recursive readdir

function fixFiles(dir) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        if (file.endsWith('.astro')) {
            const path = dir + '/' + file;
            let content = fs.readFileSync(path, 'utf8');
            
            // Remove the duplicate block generated by bad sed:
            // "import { useTranslations, defaultLang }\nimport { getRelativeLocaleUrl }\nconst lang = Astro.currentLocale || defaultLang;\nconst t = useTranslations(lang);"
            // Wait, we can just replace everything up to <style> with a clean frontmatter.
            
            // Let's match the second --- and the duplicate imports
            content = content.replace(/---\nimport { useTranslations([^<]*)/g, '---\n\n');
            // Wait, the frontmatter became:
            // ---
            // import { useTranslations...
            // ...
            // import Layout...
            // ---
            // import { useTranslations...
            // ...
            // <style>
            
            // Let's just fix it by a more precise regex.
            const badBlockEs = /import { useTranslations, defaultLang } from "(\.\.\/\.\.\/utils\/i18n)";\nimport { getRelativeLocaleUrl } from "astro:i18n";\nconst lang = Astro\.currentLocale \|\| defaultLang;\nconst t = useTranslations\(lang\);\n/g;
            const badBlockEn = /import { useTranslations, defaultLang } from "(\.\.\/\.\.\/\.\.\/utils\/i18n)";\nimport { getRelativeLocaleUrl } from "astro:i18n";\nconst lang = Astro\.currentLocale \|\| defaultLang;\nconst t = useTranslations\(lang\);\n/g;

            content = content.replace(badBlockEs, '');
            content = content.replace(badBlockEn, '');

            // Now they are gone completely. Let's add them back only once after the first ---
            const esImport = `import { useTranslations, defaultLang } from "../../utils/i18n";\nimport { getRelativeLocaleUrl } from "astro:i18n";\nconst lang = Astro.currentLocale || defaultLang;\nconst t = useTranslations(lang);\n`;
            const enImport = `import { useTranslations, defaultLang } from "../../../utils/i18n";\nimport { getRelativeLocaleUrl } from "astro:i18n";\nconst lang = Astro.currentLocale || defaultLang;\nconst t = useTranslations(lang);\n`;

            if (dir.includes('/en/')) {
                content = content.replace(/^---\n/, `---\n${enImport}`);
            } else {
                content = content.replace(/^---\n/, `---\n${esImport}`);
            }

            fs.writeFileSync(path, content);
        }
    }
}

fixFiles('./src/pages/proyectos');
fixFiles('./src/pages/en/proyectos');
